[build]
  command = "npm run build"
  publish = "dist/client"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/dashboard/admin"
  to = "/dashboard/admin"
  status = 200
  conditions = { Role = ["admin"] }

[[redirects]]
  from = "/dashboard/admin"
  to = "/"
  status = 302
