/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotographersIndexRouteImport } from './routes/photographers/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PhotographersIdRouteImport } from './routes/photographers/$id'
import { Route as DashboardPhotographerRouteImport } from './routes/dashboard/photographer'
import { Route as DashboardClientRouteImport } from './routes/dashboard/client'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as BookingsIdRouteImport } from './routes/bookings/$id'
import { Route as BookPhotographerIdRouteImport } from './routes/book/$photographerId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersIndexRoute = PhotographersIndexRouteImport.update({
  id: '/photographers/',
  path: '/photographers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersIdRoute = PhotographersIdRouteImport.update({
  id: '/photographers/$id',
  path: '/photographers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPhotographerRoute = DashboardPhotographerRouteImport.update({
  id: '/dashboard/photographer',
  path: '/dashboard/photographer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientRoute = DashboardClientRouteImport.update({
  id: '/dashboard/client',
  path: '/dashboard/client',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookPhotographerIdRoute = BookPhotographerIdRouteImport.update({
  id: '/book/$photographerId',
  path: '/book/$photographerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/book/$photographerId': typeof BookPhotographerIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/client': typeof DashboardClientRoute
  '/dashboard/photographer': typeof DashboardPhotographerRoute
  '/photographers/$id': typeof PhotographersIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/photographers/': typeof PhotographersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/book/$photographerId': typeof BookPhotographerIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/client': typeof DashboardClientRoute
  '/dashboard/photographer': typeof DashboardPhotographerRoute
  '/photographers/$id': typeof PhotographersIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/photographers': typeof PhotographersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/book/$photographerId': typeof BookPhotographerIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/client': typeof DashboardClientRoute
  '/dashboard/photographer': typeof DashboardPhotographerRoute
  '/photographers/$id': typeof PhotographersIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/photographers/': typeof PhotographersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/book/$photographerId'
    | '/bookings/$id'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/photographer'
    | '/photographers/$id'
    | '/dashboard/'
    | '/photographers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/book/$photographerId'
    | '/bookings/$id'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/photographer'
    | '/photographers/$id'
    | '/dashboard'
    | '/photographers'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/book/$photographerId'
    | '/bookings/$id'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/photographer'
    | '/photographers/$id'
    | '/dashboard/'
    | '/photographers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BookPhotographerIdRoute: typeof BookPhotographerIdRoute
  BookingsIdRoute: typeof BookingsIdRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardClientRoute: typeof DashboardClientRoute
  DashboardPhotographerRoute: typeof DashboardPhotographerRoute
  PhotographersIdRoute: typeof PhotographersIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PhotographersIndexRoute: typeof PhotographersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers/': {
      id: '/photographers/'
      path: '/photographers'
      fullPath: '/photographers/'
      preLoaderRoute: typeof PhotographersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers/$id': {
      id: '/photographers/$id'
      path: '/photographers/$id'
      fullPath: '/photographers/$id'
      preLoaderRoute: typeof PhotographersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/photographer': {
      id: '/dashboard/photographer'
      path: '/dashboard/photographer'
      fullPath: '/dashboard/photographer'
      preLoaderRoute: typeof DashboardPhotographerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/client': {
      id: '/dashboard/client'
      path: '/dashboard/client'
      fullPath: '/dashboard/client'
      preLoaderRoute: typeof DashboardClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$photographerId': {
      id: '/book/$photographerId'
      path: '/book/$photographerId'
      fullPath: '/book/$photographerId'
      preLoaderRoute: typeof BookPhotographerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BookPhotographerIdRoute: BookPhotographerIdRoute,
  BookingsIdRoute: BookingsIdRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardClientRoute: DashboardClientRoute,
  DashboardPhotographerRoute: DashboardPhotographerRoute,
  PhotographersIdRoute: PhotographersIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PhotographersIndexRoute: PhotographersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
